# =========================================================================
#     This makefile was generated by
#     Bakefile 0.2.9 (http://www.bakefile.org)
#     Do not modify, all changes will be overwritten!
# =========================================================================



# -------------------------------------------------------------------------
# These are configurable options:
# -------------------------------------------------------------------------

# Standard flags for CC 
CFLAGS ?= 

# Standard preprocessor flags (common for CC and CXX) 
CPPFLAGS ?= 

# Standard linker flags 
LDFLAGS ?= 



# -------------------------------------------------------------------------
# Do not modify the rest of this file!
# -------------------------------------------------------------------------

### Variables: ###

CPPDEPS = -MT$@ -MF$@.d -MD -MP
TEST_RAN_STORING_CFLAGS =   -Wall -Wextra -O -O2 $(CPPFLAGS) $(CFLAGS)
TEST_RAN_STORING_OBJECTS =  \
	test_ran_storing_test_ran_storing.o

### Conditionally set variables: ###



### Targets: ###

all: test_ran_storing.exe

clean: 
	-if exist .\*.o del .\*.o
	-if exist .\*.d del .\*.d
	-if exist test_ran_storing.exe del test_ran_storing.exe

test_ran_storing.exe: $(TEST_RAN_STORING_OBJECTS)
	mingw32-gcc -o $@ $(TEST_RAN_STORING_OBJECTS)   $(LDFLAGS)

test_ran_storing_test_ran_storing.o: ./test_ran_storing.c
	mingw32-gcc -c -o $@ $(TEST_RAN_STORING_CFLAGS) $(CPPDEPS) $<

.PHONY: all clean


SHELL := $(COMSPEC)

# Dependencies tracking:
-include ./*.d
