# =========================================================================
#     This makefile was generated by
#     Bakefile 0.2.9 (http://www.bakefile.org)
#     Do not modify, all changes will be overwritten!
# =========================================================================



# -------------------------------------------------------------------------
# These are configurable options:
# -------------------------------------------------------------------------

# C compiler 
CC = dmc

# Standard flags for CC 
CFLAGS = -HP99

# Standard preprocessor flags (common for CC and CXX) 
CPPFLAGS = 

# Standard linker flags 
LDFLAGS = 



# -------------------------------------------------------------------------
# Do not modify the rest of this file!
# -------------------------------------------------------------------------

### Variables: ###

TEST_RAN_STORING_CFLAGS =    -W- -A -H -s -o -O $(CPPFLAGS) $(CFLAGS)
TEST_RAN_STORING_OBJECTS =  \
	test_ran_storing_test_ran_storing.obj

### Targets: ###

all : test_ran_storing.exe

clean : 
	-if exist .\*.obj del .\*.obj
	-if exist .\*.res del .\*.res
	-if exist .\*.sym del .\*.sym
	-if exist test_ran_storing.exe del test_ran_storing.exe
	-if exist test_ran_storing.map del test_ran_storing.map

test_ran_storing.exe : $(TEST_RAN_STORING_OBJECTS)
	link /NOLOGO /SILENT /NOI /DELEXECUTABLE /EXETYPE:NT   $(LDFLAGS) $(TEST_RAN_STORING_OBJECTS),$@,test_ran_storing.map,,,

test_ran_storing_test_ran_storing.obj : .\test_ran_storing.c
	$(CC) -mn -c -o$@ $(TEST_RAN_STORING_CFLAGS) .\test_ran_storing.c

